"""Walk the TradeAI codebase and dump every source file into code.md."""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "code.md"
SKIP_DIRS = {"node_modules", "dist", ".git", "__pycache__", ".opencode"}
SKIP_FILES = {
    "package-lock.json", "tsconfig.tsbuildinfo", ".env",
    "code.py", "code.md",
}
TEXT_EXT = {".ts", ".tsx", ".js", ".jsx", ".css", ".html", ".json",
            ".md", ".cfg", ".yml", ".yaml", ".toml", ".env.example",
            ".gitignore"}


def main():
    entries: list[Path] = []
    for root, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            path = Path(root) / f
            if f in SKIP_FILES:
                continue
            if path.suffix in TEXT_EXT:
                entries.append(path)

    entries.sort()

    with open(OUT, "w", encoding="utf-8") as out:
        out.write("# TradeAI Codebase\n\n")
        out.write(f"_{len(entries)} source files — generated by code.py_\n\n---\n\n")

        for path in entries:
            rel = path.relative_to(ROOT)
            try:
                content = path.read_text(encoding="utf-8")
            except Exception as e:
                content = f"<error reading file: {e}>"

            ext = path.suffix.lstrip(".") or "text"
            out.write(f"## `{rel}`\n\n")
            out.write(f"```{ext}\n")
            out.write(content)
            out.write("\n```\n\n---\n\n")

    print(f"Wrote {len(entries)} files to {OUT}")


if __name__ == "__main__":
    main()
